class Graphics {
  constructor(p5) {
    this.height = p5.height;
    this.background = p5.background;
    this.draw = p5.draw;
    this.setup = p5.setup;
    this.preload = p5.preload;
    this.mousePressed = p5.mousePressed;
    this.mouseReleased = p5.mouseReleased;
    this.mouseMoved = p5.mouseMoved;
    this.mouseDragged = p5.mouseDragged;
    this.mouseClicked = p5.mouseClicked;
    this.mouseWheel = p5.mouseWheel;
    this.keyPressed = p5.keyPressed;
    this.keyReleased = p5.keyReleased;
    this.createCanvas = p5.createCanvas;
    this.resizeCanvas = p5.resizeCanvas;
    this.createcanvasContainer = p5.createcanvasContainer;
    this.resizecanvasContainer = p5.resizecanvasContainer;
    this.redraw = p5.redraw;
    this.loop = p5.loop;
    this.fill = p5.fill;
    this.stroke = p5.stroke;
    this.frameRate = p5.frameRate;
    this.noLoop = p5.noLoop;
    this.noFill = p5.noFill;
    this.background = p5.background;
    this.line = p5.line;
    this.keyTyped = p5.keyTyped;
    this.touchStarted = p5.touchStarted;
    this.touchMoved = p5.touchMoved;
    this.touchEnded = p5.touchEnded;
    this.touchCancelled = p5.touchCancelled;
    this.deviceMoved = p5.deviceMoved;
    this.deviceTurned = p5.deviceTurned;
    this.deviceShaken = p5.deviceShaken;
    this.keyDown = p5.keyDown;
    this.keyUp = p5.keyUp;
    this.mouseDown = p5.mouseDown;
    this.mouseUp = p5.mouseUp;
    this.mouseOut = p5.mouseOut;
    this.mouseOver = p5.mouseOver;
    this.windowResized = p5.windowResized;
  }
}
